import type { Metadata } from 'next'
import { dela, figtree } from './fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${dela.variable} ${figtree.variable}`}>
      <body>{children}</body>
    </html>
  )
}
